# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Movie.create :title => "Anchorman"
Movie.create :title => "Armageddon"
Movie.create :title => "Finding Nemo"
Movie.create :title => "Independence Day"
Movie.create :title => "Kill Bill: Vol. 1"
Movie.create :title => "Lord of the Rings: The Return of the King"
Movie.create :title => "Lord of the Rings: The Two Towers"
Movie.create :title => "Lost in Translation"
Movie.create :title => "Miss Congeniality"
Movie.create :title => "Napoleon Dynamite"
Movie.create :title => "Pearl Harbor"
Movie.create :title => "Pirates of the Caribbean"
Movie.create :title => "The Day After Tomorrow"
Movie.create :title => "Troy"
Movie.create :title => "The Green Mile"
Movie.create :title => "Pirates of the Caribbean II"
Movie.create :title => "The Patriot"
Movie.create :title => "The Royal Tenenbaums"
Movie.create :title => "The Shawshank Redemption"
Movie.create :title => "Titanic"
Movie.create :title => "Transformers I"
Movie.create :title => "Transformers II"
Movie.create :title => "Transformers III"
Movie.create :title => "Harry Potter 7 part 1"
Movie.create :title => "Harry Potter 7 part 2"

User.create :email => "Demo@test.com", :password => "password"
User.create :email => "Richard@test.com", :password => "password"
User.create :email => "Chris@test.com", :password => "password"
User.create :email => "June@test.com", :password => "password"
User.create :email => "Will@test.com", :password => "password"
User.create :email => "Renee@test.com", :password => "password"
User.create :email => "Tom@test.com", :password => "password"
User.create :email => "Ho-Joon@test.com", :password => "password"
User.create :email => "Irene@test.com", :password => "password"
User.create :email => "Vanessa@test.com", :password => "password"
User.create :email => "Biplab@test.com", :password => "password"
User.create :email => "Ben@test.com", :password => "password"
User.create :email => "Anup@test.com", :password => "password"
User.create :email => "Maidah@test.com", :password => "password"
User.create :email => "Chrissy@test.com", :password => "password"
User.create :email => "Jane@test.com", :password => "password"
User.create :email => "Tony@test.com", :password => "password"
User.create :email => "Stephen@test.com", :password => "password"
User.create :email => "Ebert@test.com", :password => "password"
User.create :email => "Netflix@test.com", :password => "password"
User.create :email => "RT@test.com", :password => "password"
User.create :email => "RTaudience@test.com", :password => "password"
User.create :email => "MC@test.com", :password => "password"
User.create :email => "MCuser@test.com", :password => "password"
User.create :email => "IMDB@test.com", :password => "password"
